const books = [
    {
      status: "active",
      title: "Clean Code: A Handbook of Agile Software Craftsmanship",
      slug: "clean-code",
      year: 2008,
      author: "Robert C. Martin",
      imageURL: "https://m.media-amazon.com/images/I/41SH-SvWPxL.jpg",
      imageList: ["https://m.media-amazon.com/images/I/41SH-SvWPxL.jpg"],
      isbn: 9780132350884,
      genre: "Software Development",
      description:
        "A book about writing clean and maintainable code, with principles and best practices for software developers.",
      available: true,
      expectedAvailabilityDate: null,
      averageRating: 4.7,
      addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
      lastUpdatedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    },
    {
      status: "active",
      title: "The Pragmatic Programmer: Your Journey To Mastery",
      slug: "the-pragmatic-programmer",
      year: 1999,
      author: "Andrew Hunt and David Thomas",
      imageURL: "https://m.media-amazon.com/images/I/41as+WafrFL.jpg",
      imageList: ["https://m.media-amazon.com/images/I/41as+WafrFL.jpg"],
      isbn: 9780135957059,
      genre: "Software Development",
      description:
        "A classic book covering pragmatic thinking, career development, and software craftsmanship.",
      available: true,
      expectedAvailabilityDate: null,
      averageRating: 4.8,
      addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
      lastUpdatedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    },
    {
      status: "active",
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      slug: "design-patterns",
      year: 1994,
      author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
      imageURL: "https://m.media-amazon.com/images/I/41T0lDqaI+L.jpg",
      imageList: ["https://m.media-amazon.com/images/I/41T0lDqaI+L.jpg"],
      isbn: 9780201633610,
      genre: "Software Engineering",
      description: "The classic book on design patterns in software engineering.",
      available: true,
      expectedAvailabilityDate: null,
      averageRating: 4.6,
      addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
      lastUpdatedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    },
    {
      status: "active",
      title: "Refactoring: Improving the Design of Existing Code",
      slug: "refactoring",
      year: 1999,
      author: "Martin Fowler",
      imageURL: "https://m.media-amazon.com/images/I/518FqJvR9aL.jpg",
      imageList: ["https://m.media-amazon.com/images/I/518FqJvR9aL.jpg"],
      isbn: 9780201485677,
      genre: "Software Engineering",
      description: "A guide to improving code structure and design through refactoring techniques.",
      available: true,
      expectedAvailabilityDate: null,
      averageRating: 4.7,
      addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
      lastUpdatedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    },
    {
      status: "active",
      title: "You Don't Know JS: Scope & Closures",
      slug: "you-dont-know-js-scope-closures",
      year: 2014,
      author: "Kyle Simpson",
      imageURL: "https://m.media-amazon.com/images/I/41uPjEenkFL.jpg",
      imageList: ["https://m.media-amazon.com/images/I/41uPjEenkFL.jpg"],
      isbn: 9781449335588,
      genre: "JavaScript",
      description: "A deep dive into JavaScript scope and closures.",
      available: true,
      expectedAvailabilityDate: null,
      averageRating: 4.5,
      addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
      lastUpdatedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    },
    {
      status: "active",
      title: "The Mythical Man-Month: Essays on Software Engineering",
      slug: "the-mythical-man-month",
      year: 1975,
      author: "Frederick P. Brooks Jr.",
      imageURL: "https://m.media-amazon.com/images/I/41-D+wLfJYL.jpg",
      imageList: ["https://m.media-amazon.com/images/I/41-D+wLfJYL.jpg"],
      isbn: 9780201835953,
      genre: "Software Engineering",
      description: "A classic book on software project management and engineering.",
      available: true,
      expectedAvailabilityDate: null,
      averageRating: 4.4,
      addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
      lastUpdatedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    }
  ];

  export default books;